services:

  microservice-anti-fraud:
    build:
      context: .
      dockerfile: Dockerfile
    image: angelmr01/microservice-antifraud:latest
    container_name: antifraud-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=${MONGO_DOCKER_URI}
      - MONGO_DB=antifraud_db
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
      - ACCOUNTS_MS_URL=${ACCOUNTS_MS_URL}
      - BANK_STATEMENTS_MS_URL=${BANK_STATEMENTS_URL}
      - ACCOUNTS_BLOCK_TIMEOUT_MS=3000
      - REDIS_URL=redis://redis-cache:6379
      - TRANSACTION_CACHE_TTL_SECONDS=300
    depends_on:
      mongo:
        condition: service_healthy
      redis-cache:
        condition: service_started
    networks:
      - bankus-net
    restart: on-failure


  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=antifraud_db
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    healthcheck:
      # Comando que Docker ejecutará dentro del contenedor para ver si está vivo
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s   # Prueba cada 10 segundos
      timeout: 5s     # Si tarda más de 5s, falla
      retries: 5
      start_period: 5s # Dale 5s de gracia al inicio para arrancar


  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bankus-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  mongo-data:

networks:
  bankus-net:
    driver: bridge