version: '3.9'

services:

  mongo-db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      # Comando que Docker ejecutará dentro del contenedor para ver si está vivo
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s   # Prueba cada 10 segundos
      timeout: 5s     # Si tarda más de 5s, falla
      retries: 5
      start_period: 5s # Dale 5s de gracia al inicio para arrancar

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Puerto de comunicación (Donde se conectan los microservicios)
      - "15672:15672" # Puerto del Panel Web de Administración
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s # RabbitMQ tarda un poco más en arrancar que Mongo


  app-antifraude:
    build: .
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=${MONGO_DOCKER_URI}
      
        # Formato: amqp://usuario:contraseña@nombre_servicio_docker:puerto
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongo-db:
        # No arranques hasta que mongo esté "Healthy", es decir, arrancado y listo.
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

    restart: on-failure


volumes:
  mongo-data: