version: '3.9'

services:

  mongo-db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      # Comando que Docker ejecutará dentro del contenedor para ver si está vivo
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s   # Prueba cada 10 segundos
      timeout: 5s     # Si tarda más de 5s, falla
      retries: 5
      start_period: 5s # Dale 5s de gracia al inicio para arrancar


  app-antifraude:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_DOCKER_URI}
    depends_on:
      mongo-db:
        # No arranques hasta que mongo esté "Healthy", es decir, arrancado y listo.
        condition: service_healthy
    restart: on-failure


volumes:
  mongo-data: